//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AICC_J_HIGH_SCORE
    {
        public decimal J_HIGH_SCORE_NUM { get; set; }
        public string COURSE_ID { get; set; }
        public string STUDENT_ID { get; set; }
        public string OBJ_OBJECTIVE_ID { get; set; }
        public string OBJ_HIGH_SCORE { get; set; }
        public string OBJ_HIGH_STATUS { get; set; }
        public Nullable<System.DateTime> OBJ_FIRST_DATE { get; set; }
        public string SESSION_ID { get; set; }
        public Nullable<int> uidcount { get; set; }
        public Nullable<int> timems { get; set; }
        public Nullable<int> length { get; set; }
    }
}
