//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHW_CONTENT_TYPE_BASE
    {
        public int TYPE_ID { get; set; }
        public string TYPE_NAME { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> CHW_PAPER_TYPE { get; set; }
    }
}
