//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHW_EXAM_PREF
    {
        public int EXAM_PREF_ID { get; set; }
        public Nullable<int> EXAM_ID { get; set; }
        public string USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> LAST_DATE { get; set; }
        public Nullable<int> TOTAL_TIME { get; set; }
        public Nullable<int> LAST_SCORE { get; set; }
        public Nullable<int> HIGH_SCORE { get; set; }
        public Nullable<int> ATTEMPT_NUMBER { get; set; }
        public Nullable<int> CHW_PAPER_TYPE { get; set; }
        public string CHW_SESSION_ID { get; set; }
        public Nullable<float> USER_CREDIT_HOUR { get; set; }
    }
}
