//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSEWARE
    {
        public Nullable<decimal> STATUS { get; set; }
        public decimal COURSE_ID { get; set; }
        public string COURSE_NAME { get; set; }
        public string MENTOR_NAME { get; set; }
        public Nullable<System.DateTime> COURSE_CREATEDATE { get; set; }
        public Nullable<decimal> TYPE_ID { get; set; }
        public string COURSE_NUMBER { get; set; }
        public Nullable<decimal> MASTERY_SCORE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> LIMIT_TIME { get; set; }
        public Nullable<short> AUTO_OVER { get; set; }
        public Nullable<short> AUTO_REG { get; set; }
        public Nullable<int> AUTHLIMIT { get; set; }
        public Nullable<int> COURSE_FLAG { get; set; }
        public Nullable<double> course_price { get; set; }
        public Nullable<int> distributed_flag { get; set; }
        public string content_source { get; set; }
        public Nullable<int> exam_id { get; set; }
        public Nullable<double> credit_hour { get; set; }
        public Nullable<double> duration { get; set; }
        public string teachername { get; set; }
        public Nullable<int> topnum { get; set; }
        public string COURSE_TYPE { get; set; }
        public int Recommend { get; set; }
    }
}
