//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JY_Atype
    {
        public int ID { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> IsLink { get; set; }
        public string Url { get; set; }
        public string Img { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> fuser { get; set; }
        public string ClassId { get; set; }
        public string ClassList { get; set; }
        public string ClassPre { get; set; }
        public Nullable<int> ClassTj { get; set; }
        public Nullable<int> ClassOrder { get; set; }
    }
}
