//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jy_Article
    {
        public int id { get; set; }
        public string title { get; set; }
        public string Author { get; set; }
        public string source { get; set; }
        public string content { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ClickRate { get; set; }
        public Nullable<int> IsShow { get; set; }
        public Nullable<int> IsTop { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
