//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JY_Channel
    {
        public int ChannelID { get; set; }
        public string SchoolName { get; set; }
        public string ChannelName { get; set; }
        public string ChannelShortName { get; set; }
        public string ChannelItemUnit { get; set; }
        public string ReadMe { get; set; }
        public string ChannelPicUrl { get; set; }
        public Nullable<short> OrderID { get; set; }
        public Nullable<int> OpenType { get; set; }
        public Nullable<int> ChannelType { get; set; }
        public string LinkUrl { get; set; }
        public string ChannelDir { get; set; }
        public Nullable<int> ModuleType { get; set; }
        public int Disabled { get; set; }
        public Nullable<int> parentid { get; set; }
    }
}
