//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JY_Lession
    {
        public int id { get; set; }
        public string title { get; set; }
        public string teacher { get; set; }
        public string source { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string img { get; set; }
        public string lessions { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<int> LessionType { get; set; }
        public Nullable<int> ShowType { get; set; }
        public string Course_number { get; set; }
        public string kclx { get; set; }
        public string kcjj { get; set; }
        public string xs { get; set; }
        public string xf { get; set; }
        public Nullable<int> ScreenWidth { get; set; }
        public Nullable<int> ScreenHeight { get; set; }
    }
}
