//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JY_UrlMms
    {
        public int ID { get; set; }
        public string UID { get; set; }
        public string Mms { get; set; }
        public Nullable<int> Type { get; set; }
        public string Note { get; set; }
        public string title { get; set; }
        public Nullable<double> Video_Length { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string CourseNmber { get; set; }
    }
}
