//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Push
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Conetent { get; set; }
        public string UserId { get; set; }
        public System.DateTime Time { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
    }
}
