//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticleComment
    {
        public int Id { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public Nullable<int> ArtId { get; set; }
        public string Context { get; set; }
        public Nullable<int> thumbsup { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime CreatTime { get; set; }
    }
}
