//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAppeal
    {
        public int ID { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PWD { get; set; }
        public string USER_PWD_QUT { get; set; }
        public string USER_PWD_ANS { get; set; }
        public Nullable<System.DateTime> USER_BRI_DATE { get; set; }
        public string USER_TEL { get; set; }
        public string USER_EMAIL { get; set; }
        public string id_card { get; set; }
        public string USER_IP { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
