//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_GROUP
    {
        public decimal USER_GROUP_ID { get; set; }
        public string USER_GROUP_NAME { get; set; }
        public Nullable<decimal> PER_USER_GROUP { get; set; }
        public Nullable<int> duchy { get; set; }
        public Nullable<int> G_ParentID { get; set; }
        public Nullable<int> G_ShowOrder { get; set; }
        public Nullable<int> G_Level { get; set; }
        public Nullable<int> G_ChildCount { get; set; }
        public Nullable<byte> G_Delete { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
