//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCredit
    {
        public string User_ID { get; set; }
        public Nullable<double> ExamCredit { get; set; }
        public Nullable<double> CourseCredit { get; set; }
        public Nullable<double> virCredit { get; set; }
        public Nullable<double> OtherCredit { get; set; }
    }
}
