//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public Nullable<short> USER_STATUS { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_TIME { get; set; }
        public Nullable<decimal> USER_GROUP_ID { get; set; }
        public string USER_ID { get; set; }
        public decimal USER_NM { get; set; }
        public Nullable<short> USER_TYPE { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PWD { get; set; }
        public string USER_PWD_QUT { get; set; }
        public string USER_PWD_ANS { get; set; }
        public Nullable<System.DateTime> USER_BRI_DATE { get; set; }
        public Nullable<short> USER_SEX { get; set; }
        public string USER_TEL { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_INTRODUCE { get; set; }
        public string USER_IP { get; set; }
        public string USER_PROXY_IP { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> USER_BUSINESS_NM { get; set; }
        public Nullable<decimal> COURSE_ONLINE { get; set; }
        public Nullable<decimal> OTHER_ID { get; set; }
        public Nullable<int> TOP_GROUP_ID { get; set; }
        public Nullable<int> USER_FLAG { get; set; }
        public Nullable<int> LOGIN_TIMES { get; set; }
        public Nullable<int> zc { get; set; }
        public Nullable<int> zz_sf { get; set; }
        public Nullable<int> zj { get; set; }
        public Nullable<System.DateTime> user_worktime { get; set; }
        public string OTHER_ID_1 { get; set; }
        public string OTHER_ID_2 { get; set; }
        public string OTHER_ID_3 { get; set; }
        public string OTHER_ID_4 { get; set; }
        public string OTHER_ID_5 { get; set; }
        public Nullable<int> borrow { get; set; }
        public Nullable<System.DateTime> borrow_time { get; set; }
        public string borrow_unit { get; set; }
        public Nullable<int> post_id { get; set; }
        public Nullable<int> xueli_id { get; set; }
        public Nullable<int> Degree_id { get; set; }
        public Nullable<int> character_id { get; set; }
        public string id_card { get; set; }
        public Nullable<System.DateTime> start_on_time { get; set; }
        public Nullable<int> default_credit_hour { get; set; }
        public Nullable<double> need_score { get; set; }
        public Nullable<int> user_state { get; set; }
        public Nullable<System.DateTime> cd_sj { get; set; }
        public Nullable<int> gwy_sf { get; set; }
        public string Extension { get; set; }
        public string EName { get; set; }
        public string Licence { get; set; }
        public string Mac { get; set; }
        public string MobileNo { get; set; }
        public string UserNO { get; set; }
        public Nullable<System.DateTime> WorkEndDate { get; set; }
        public string CompanyMail { get; set; }
        public string PhotoUrl { get; set; }
        public string ExtendField { get; set; }
        public Nullable<int> Title { get; set; }
        public string IC_CARD { get; set; }
        public string mingzu { get; set; }
        public Nullable<int> Marriage { get; set; }
        public Nullable<int> fristxueli { get; set; }
        public string S_USER_BUSINESS_NM { get; set; }
        public Nullable<int> hightxueli { get; set; }
        public string other_town { get; set; }
        public Nullable<int> ActiveDegree { get; set; }
    }
}
